---
title: "Arbeidskrav i Anvendt by- og regionaløkonomi"
author: "Gruppe 2"
format: html
editor: visual
---

## Datainnhenting

```{r}
load("nor_knr24_vec.rdata")
load("newknr.rdata")
```

```{r}
#| label: setup
#| message: false
#| echo: true
#| warning: false

library(tidyverse)
library(readxl)
library(sf)
library(spdep)
library(writexl)
library(PxWebApiData)
library(modelsummary)
```

### Folketall.

```{r}
#| cache: true
beftot <- PxData12(
  "https://data.ssb.no/api/v0/no/table/07459/",
  Region = list("agg:KommSummer", knr24),
  Tid = as.character(1986:2025),
  Alder = list("agg:TodeltGrupperingB", c("H17", "H18"))) |> 
  select(Region, år, value) |> 
  group_by(Region, år) |> 
  summarise(beftot = sum(value), .groups = "drop") |> 
  rename(kommunenummer = Region) |> 
  filter(!kommunenummer %in% c("K-21-22", "K-23", "K-Rest")) |> 
  mutate(kommunenummer = str_sub(kommunenummer, 3, 6))
```

```{r}
#| cache: true
befendr <- PxData12(
  "https://data.ssb.no/api/v0/no/table/07459/",
  Region = list("agg:KommSummer", knr24),
  Tid = c("2000", "2025"),
  Alder = list("agg:TodeltGrupperingB", c("H17", "H18"))) |> 
  group_by(Region, år) |> 
  summarise(beftot = sum(value), .groups = "drop") |> 
  pivot_wider(
    names_prefix = "beftot",
    names_from = år,
    values_from = beftot
  ) |> 
  rename(kommunenummer = Region) |> 
  filter(!kommunenummer %in% c("K-21-22", "K-23", "K-Rest")) |> 
  mutate(kommunenummer = str_sub(kommunenummer, 3, 6)) |>
  mutate(bef_endrtot = (beftot2025/beftot2000)*100) |> 
  mutate(bef_endrtot = case_when(
    is.infinite(bef_endrtot) ~ 100,
    .default = bef_endrtot
  )) |>
  select(kommunenummer, bef_endrtot)
```

```{r}
bef <- left_join(beftot, befendr, by = join_by("kommunenummer"))
```

### Demografiske data.

```{r}
# demografiske mellom 1986 og 2025

demografiske_kjonn <- PxData12(
  "https://data.ssb.no/api/v0/no/table/07459/",
  Region = list("agg:KommSummer", knr24),
  Tid    = as.character(1986:2025),
  Kjonn  = c("1","2"),
  Alder  = list("agg:TiAarigGruppering",
                c("F00-09","F10-19","F20-29","F30-39","F40-49",
                  "F50-59","F60-69","F70-79","F80-89","F90-99","F100G10+"))
) |>
  select(Region, år, Kjonn, alder, value) |>
  mutate(
    kjønn = recode(as.character(Kjonn),
                   "1"="Menn","2"="Kvinner",
                   .default=as.character(Kjonn))
  ) |>
  group_by(Region, år, kjønn, alder) |>
  summarise(bef = sum(value, na.rm = TRUE), .groups = "drop") |>
  rename(kommunenummer = Region) |>
  filter(!kommunenummer %in% c("K-21-22", "K-23", "K-Rest")) |>
  mutate(kommunenummer = str_sub(kommunenummer, 3, 6)) |>
  select(kommunenummer, år, kjønn, alder, bef)

```

```{r}
# demografi etter aldersgruppe
demografi <- demografiske_kjonn |>
  mutate(
    aldersgruppe = case_when(
      alder %in% c("0-9 år", "10-19 år") ~ "0-19",
      alder == "20-29 år"               ~ "20-29",
      alder %in% c("30-39 år", "40-49 år") ~ "30-45",
      alder %in% c("50-59 år", "60-69 år") ~ "45-66",
      TRUE                               ~ "67+"
    )
  ) |>
  group_by(kommunenummer, år, kjønn, aldersgruppe) |>
  summarise(bef = sum(bef, na.rm = TRUE), .groups = "drop")

```

```{r}
demografi_total <- demografi |>
  group_by(kommunenummer, år, aldersgruppe) |>
  summarise(
    bef = sum(bef, na.rm = TRUE),
    .groups = "drop"
  )

```

### Sentralitetsindeksen for norske kommuner.

```{r}
#Leser av excel-filene
sentralitet2017 <-
  read_xlsx("./data/sentralitet 2017.xlsx")
sentralitet2020 <- 
  read_xlsx("./data/sentralitet 2020 kommuner.xlsx")
sentralitet2023 <-
  read_xlsx("./data/sentralitet 2023-2024 kommuner.xlsx")
# Slår sammen tabellene fra 2020/2023 slik at vi kan se utvikling. 
Sentralitet <-
  newknr %>%
  left_join(sentralitet2017, by = c("knr" = "Kommunenummer 2018"), keep = FALSE) %>%
  left_join(sentralitet2020, by = "knr", keep = FALSE) %>%
  left_join(sentralitet2023, by = c("knr2023" = "knr 2024"), keep = FALSE)%>%
  # Sammenligner sentralitetsindeks i 2020 og 2023.  
  mutate('Endring sentralitetsindeks 2020/2023' = `Indeks 2020` - `Indeks 2023`)
```

```{r}
Sentralitet <- Sentralitet |>
  rename("kommunenummer" = knr2023) |>
  select(-knr)
```

### Prosentvis arbeidsledighet.

```{r}
SSb_Arbledig <- PxData12(
  "https://data.ssb.no/api/v0/no/table/13563/",
  Region = list("agg:KommSummer", knr24),
  Tid = as.character(2008:2024),
  HovArbStyrkStatus = c("A", "A.09"),
  Alder = "15+",
  InnvandrKat = "A-G") |>
  select(Region, år, HovArbStyrkStatus, value) |>
  pivot_wider(
    names_from  = HovArbStyrkStatus,
    values_from = value
  ) |>
  rename(
    arbeidsstyrke = A,
    registrerte_ledige = `A.09`) |>
  rename(kommunenummer = Region) |> 
  filter(!kommunenummer %in% c("K-21-22", "K-23", "K-Rest")) |> 
    mutate(
    kommunenummer = str_sub(kommunenummer, 3, 6),
    prosent_arbledig = if_else(
    is.na(arbeidsstyrke) | arbeidsstyrke == 0,
    NA_real_,
    round(100 * registrerte_ledige / arbeidsstyrke, 2)))
```

```{r}

# NA verdier har ikke blitt fjernet, hvis du lurte :)
# Leser inn excel tabell NavTabell 1995-2024.xlsx
NAV <- read_excel("NavTabell 1995-2024.xlsx",
                  sheet = 1,
                  skip = 4,
                  col_types = "text")

# Gjør om Karakterer til Nummeriske tall
NAV <- NAV |>
  mutate(
    År = as.numeric(År),
    Kommunenr = as.numeric(Kommunenr)
  )

NAV <- NAV |>
  mutate(
    beholdning = as.numeric(Beholdning),
    andel = as.numeric(`Andel av arbeidsstyrken`)
  ) |>
  filter(Kommunenr != -1)

# Lager et eget data for nav_aar, der en gjør om månedstall til ett gjennomsnittstall for hvert år i hver kommune.
nav_aar <- NAV |>
  group_by(Kommunenr, År) |>
  rename(kommunenummer = Kommunenr, år = År ) |>
  summarise(
    prosent_ledige_i_året = mean(andel, na.rm = TRUE),
    antall_ledige_i_året = mean(beholdning, na.rm = TRUE),
    .groups = "drop"
  )

# Sletter NAV grunnet til at de viktige tallene vi trenger ligger i nav_aar
 rm(NAV)
```

### Sysselsetting.

```{r}
#| warning: false

syss <- pxwebData12(
  "https://data.ssb.no/api/v0/no/table/11616",
  Region = list("*"),
  ContentsCode = c("Arbeidssted"),
  Tid = as.character(2000:2024),
  Alder = "15-74"
)

```

```{r}
syss <- syss |>
  select(knr = Region, år, Arbeidssted) |>
  left_join(newknr, join_by(knr)) |>
  group_by(knr2023, år) |>
  summarise(Arbeidssted = sum(Arbeidssted),
            .groups = "drop") |>
  filter(knr2023 != "9999") |>
  rename(kommunenummer = knr2023)
```

```{r}
syssendr0024 <- syss |> 
  filter(år %in% c(2000, 2024)) |> 
   pivot_wider(
     names_prefix = "syss",
     names_from = år,
     values_from = Arbeidssted
   ) |> 
  mutate(syssendr0024 = round(((syss2024-syss2000)/syss2000)*100, digits = 2)) |> 
  mutate(syssendr0024 = case_when(
    is.infinite(syssendr0024) ~ 0,
    .default = syssendr0024
  )) |> 
  select(-c(syss2000, syss2024)) 
```


### Gjennomsnittlig kvadratmeterpris for bolig.

```{r}
# Hent metadata for tabell 06035
meta <- ApiData(
  "https://data.ssb.no/api/v0/no/table/06035/",
  returnMetaFrames = TRUE
)

# Finn alle kommuner (4-sifrede kommunenummer)
# Dette gir kommunenivå i gjeldende inndeling
kommune_values <- meta$Region |>
  transmute(kommunenummer = values) |>
  filter(str_detect(kommunenummer, "^\\d{4}$")) |>
  pull(kommunenummer)


# Hent boligomsetninger fra API
#    - År: 2002–2024
#    - Boligtype: Enebolig (01) og Leilighet (03)
#    - Variabel: Kvadratmeterpris
bolig <- ApiData12(
  "https://data.ssb.no/api/v0/no/table/06035/",
  Region = kommune_values,
  Tid = as.character(2002:2024),
  Boligtype = c("01", "03"),
  ContentsCode = "KvPris"
) |>
  select(Region, Tid, Boligtype, value) |>
  rename(
    kommunenummer = Region,
    år = Tid,
    kvpris = value
  ) |>
  mutate(
    boligtype_txt = case_when(
      Boligtype == "01" ~ "Enebolig",
      Boligtype == "03" ~ "Leilighet",
      TRUE ~ Boligtype
    )
  )|>
  filter(!is.na(kvpris))

```

### Utdanningsnivå.

```{r}

utdanning <- pxwebData12(
  "https://data.ssb.no/api/v0/no/table/09429/",
  Region = list("*"),
  Tid = as.character(c(1970, 1980:2024)),
  Nivaa = c("01", "02a", "11", "03a", "04a", "09a"), # 6 nivå
  Kjonn = c("1", "2"), # 1 er Menn，og 2 er Kvinner
  ContentsCode = "Personer"
) |> 
  select(Region, år, nivå, Nivaa, Kjonn, Personer) |>
  rename(knr = Region)
```

```{r}
utdanning <- left_join(newknr, utdanning, join_by(knr)) |>
  rename(kommunenummer = knr2023) |>
  filter(!is.na(kommunenummer)) |>
  group_by(kommunenummer, år, nivå, Nivaa, Kjonn) |>
  summarise(
    Personer = sum(Personer, na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(
    Personer = if_else(Personer == 0, NA_real_, Personer)
  ) |>
  filter(!kommunenummer %in% c("K-21-22", "K-23", "K-Rest")) |>
  left_join(beftot, by = c("kommunenummer", "år")) |>
  mutate(
    utdanand = if_else(
      is.na(beftot) | beftot == 0 | is.na(Personer),
      NA_real_,
      100 * Personer / beftot
    )
  )|>
  filter(
    !is.na(Personer),
    !is.na(beftot),
    !is.na(utdanand)
  )

```

### Ut- og innflyttinger pr 1000 innbyggere.

```{r}
#| warning: false
flyttper1000 <- pxwebData12(
  "https://data.ssb.no/api/v0/no/table/13255/",
  Region = list("*"),
  Tid = as.character(2010:2024),
  Alder = c("18-29", "30+")) |>
  select(Region, år, Alder, Innflytting, Utflytting) |> 
  rename(knr = Region,
         alder = Alder)
```

```{r}
flyttper1000 <- left_join(newknr, flyttper1000, join_by(knr)) |>
  rename(kommunenummer = knr2023) |>
  group_by(kommunenummer, år, alder) |>
  summarise(innflytting = sum(Innflytting),
            utflytting = sum(Utflytting), 
            .groups = "drop") |>
  filter(!kommunenummer %in% c("K-21-22", "K-23", "K-Rest")) |>
  mutate(nettoflytt = innflytting - utflytting) |>
  left_join(beftot, join_by(kommunenummer, år)) |> 
  mutate(innper1000 = innflytting/beftot*1000,
         utper1000 = utflytting/beftot*1000,
         nettoflyttper1000 = innper1000 - utper1000) |>
  select(kommunenummer, år, alder, innper1000, utper1000, nettoflyttper1000)
```

```{r}
#| warning: false
flyttkat <- pxwebData12(
  "https://data.ssb.no/api/v0/no/table/13255/",
  Region = list("*"),
  Tid = as.character(2010:2024),
  Alder = c("18-29", "30+")) |>
  select(Region, år, Innflytting, Utflytting) |> 
  rename(knr = Region)

flyttkat <- left_join(newknr, flyttkat, join_by(knr)) |>
  rename(kommunenummer = knr2023) |>
  group_by(kommunenummer, år) |>
  summarise(innflytting = sum(Innflytting),
            utflytting = sum(Utflytting), 
            .groups = "drop") |>
  filter(!kommunenummer %in% c("K-21-22", "K-23", "K-Rest")) |>
  left_join(beftot, join_by(kommunenummer, år)) |>
  mutate(totinnper1000 = innflytting/beftot*1000,
         totutper1000 = utflytting/beftot*1000,
         nettototflytt = totinnper1000 - totutper1000) |>
  select(kommunenummer, år, nettototflytt) |>
  mutate(kategori = ifelse(nettototflytt > 0, "inn_mest", "ut_mest")) |>
  select(-nettototflytt)
```

```{r}
flytt <- left_join(flyttper1000, flyttkat, by = join_by(kommunenummer, år))
```

### Inn- og utpendling.

```{r}
#| warning: false
pendl <- pxwebData12(
  "11616",
  Region = list("*"),
  ContentsCode = c("Bosatt", "Innpendlere", "Utpendlere", "Arbeidssted"),
  Tid = as.character(2000:2024),
  Alder = "15-74"
) |>
  pivot_longer(
    cols = c(Bosatt, Innpendlere, Utpendlere, Arbeidssted),
    names_to = "ContentsCode",
    values_to = "value"
  )
```

```{r}
# Aggregerer tallene over kjønn ved å summere menn (Kjonn = 1)
# og kvinner (Kjonn = 2), slik at vi får tall for begge kjønn
pendl_begge <- pendl |>
  mutate(
    Region = as.character(Region),
    år  = as.integer(år)
  ) |>
  # Beholder kun observasjoner for menn og kvinner
  filter(Kjonn %in% c(1, 2)) |>
  group_by(Region, år, ContentsCode) |>
  # Summerer over kjønn ved å gruppere på kommune, år og innhold
  summarise(
    antall = sum(value, na.rm = TRUE),
    .groups = "drop"
  ) |>
  # Gir innholdsvariabelen et mer beskrivende navn
  rename(situasjon = ContentsCode)

```

```{r}
#  Gjør datasettet bredt slik at hver situasjon
#  (Bosatt, Arbeidssted, Innpendlere, Utpendlere) blir en egen kolonne

pendl_begge <- pendl_begge |>
  pivot_wider(
    names_from  = situasjon,
    values_from = antall
  )
```

```{r}
# Beregner indikatorene som etterspørres i oppgaven
pendl_per1000 <- pendl_begge |>
  mutate(
    # Innpendling pr 1000 arbeidsplasser i kommunen
    innpend_per1000_arbpl = ifelse(Arbeidssted > 0,
                                   Innpendlere / Arbeidssted * 1000,
                                   NA_real_),

    # Utpendling pr 1000 arbeidstakere (bosatt i kommunen)
    utpend_per1000_bosatt = ifelse(Bosatt > 0,
                                   Utpendlere / Bosatt * 1000,
                                   NA_real_),

    # (valgfritt) netto pendling
    pendlingsbalanse = Innpendlere - Utpendlere
  ) |>
  select(
    Region, år,
    Bosatt, Arbeidssted, Innpendlere, Utpendlere,
    innpend_per1000_arbpl, utpend_per1000_bosatt,
    pendlingsbalanse
  )
```

```{r}
library(writexl)
```

```{r}
sheets <- list(
  "bef"            = bef,
  "demografi"     = demografi,
  "demografi_total" = demografi_total,
  "SSb_Arbledig"   = SSb_Arbledig,
  "bolig"          = bolig,
  "utdanning"     = utdanning,
  "flytt"          = flytt,
  "pendl_per1000" = pendl_per1000,
  "Sentralitet"   = Sentralitet,
  "nav_aar"  = nav_aar,
  "syss" = syss
)

write_xlsx(sheets, "data_export.xlsx")
```


