---
title: "Kladd_601622"
editor: visual
author: ""
institute: "HVL"
date: last-modified
date-format: "dddd D MMM, YYYY"
abstract: ""
number-sections: true
number-depth: 3
lang: NO_nb
csl: apa7.csl
crossref:
  fig-prefix: figur
  tbl-prefix: tabell
  fig-title: Figur
  tbl-title: Tabell
  lof-title: "Figurliste"
  lot-title: "Tabelliste"
format:
  html: default
  typst:
    papersize: a4
    toc: true
    toc-title: Innholdsfortegnelse
    documentclass: article
    number-sections: true
    keep-tex: true
    fig-pos: "H"
    output-file: "Kladd_601622"
    citeproc: true
  pdf:
    documentclass: article
    toc:  true
    toc-title: Innholdsfortegnelse
    number-sections: true
    keep-tex: true
    papersize: A4
    fig-pos: "H"
    output-file: "Kladd_601622"
editor_options:
  markdown:
    wrap: 72
    canonical: true
    chunk_output_type: console
echo: false
eval: true
bibliography: ArbRef.bib
nocite: '@*'
---

```{r}
#| label: setup
#| message: false
#| warning: false
library(knitr)
library(tidyverse)
library(lubridate)
library(PxWebApiData)
library(flextable)
library(dplyr)
options(
  paged.print = FALSE,
  scipen = 999
  )
```

```{r}
#| eval: false
# Lage en bib fil for brukte R pakker 
packs <- c(
  "knitr"
  )
write_bib(
  packs,
  file = "ArbRef.bib"
  )
rm(packs)
```

# Innhentning av data

## Folketall

```{r}
load("nor_knr24_vec.rdata")
load("newknr.rdata")
```

```{r}
#| cache: true
beftot <- PxData12(
  "https://data.ssb.no/api/v0/no/table/07459/",
  Region = list("agg:KommSummer", knr24),
  Tid = as.character(2000:2025),
  Alder = list("agg:TodeltGrupperingB", c("H17", "H18"))) |> 
  select(Region, år, value) |> 
  group_by(Region, år) |> 
  summarise(bef = sum(value), .groups = "drop") |> 
  pivot_wider(
    names_prefix = "bef",
    names_from = år,
    values_from = bef
  ) |> 
  rename(kommunenummer = Region) |> 
  filter(!kommunenummer %in% c("K-21-22", "K-23", "K-Rest")) |> 
  mutate(kommunenummer = str_sub(kommunenummer, 3, 6)) |>
  mutate(bef_endrtot = (bef2025/bef2000)*100) |> 
  mutate(bef_endrtot = case_when(
    is.infinite(bef_endrtot) ~ 100,
    .default = bef_endrtot
  ))
```

```{r}
#| cache: true
befald <- PxData12(
  "https://data.ssb.no/api/v0/no/table/07459/",
  Region = list("agg:KommSummer", knr24),
  Tid = as.character(2000:2025),
  Alder = list("agg:TiAarigGruppering", c("F00-09", "F10-19", "F20-29", "F30-39", "F40-49", "F50-59", "F60-69", "F70-79", "F80-89", "F90-99", "F100G10+"))) |> 
  select(Region, år, alder, value) |> 
  group_by(Region, år, alder) |> 
  summarise(bef = sum(value), .groups = "drop") |> 
  pivot_wider(
    names_prefix = "bef",
    names_from = år,
    values_from = bef
  ) |> 
  rename(kommunenummer = Region) |> 
  filter(!kommunenummer %in% c("K-21-22", "K-23", "K-Rest")) |> 
  mutate(kommunenummer = str_sub(kommunenummer, 3, 6))
```

```{r}
bef <- left_join(beftot, befald, by = join_by("kommunenummer"))
```

# Tilstand og utvikling for ulike variabler

Som grunnlag for å lage kartvisualiseringer kan dere bruke filen
knr_kart_norge_kystlinje.gpkg, som dere finner i Canvas. Lag
kartframstillinger for:

• Prosentvis folketallsvekst for ulike kommuner etter år 2000

# Litteraturliste

::: {#refs}
:::

\listoffigures
\listoftables

# Appendiks {.unnumbered}
